### ISSUE TITLE
I think you forgot to bundle the touchscreen firmware?

### ISSUE THREAD

**Issue by AXKuhta** [freak07/Kirisakura_TEQUILA_Zenfone_7#1]
The directory `drivers/input/touchscreen/focaltech_touch_3518U/include/` appears to be missing from the repository, leading to a build error.

Don't know if that's intentional or not.

Manually adding the folder works. Doing `git add -f drivers/` makes git pick it up.

Also, you might have the first reproduction:

![Reproduced build running](https://i.imgur.com/ryd7MHA.jpg)

So glad someone picked up this device!

**Comment by freak07** [comment]
indeed, these files were not visible to git. pushed a new branch, files are included there now. 
Thanks for making me aware of it :)

Happy to hear you got it building, congrats :)
